### ISSUE TITLE
[Internal Server Error]

### ISSUE THREAD

**Issue by BenP51** [StudentRND/CodeDay#10]
# Error report

Status Code: 500
Path: `//`

**Comment by rodrigoargumedo** [comment]
CodeDay is working for me. AWS can be wacky at times upon uptime of the servers. Does this error still reproduce?

**Comment by BenP51** [comment]
I was using a public computer, which I no longer have access to but it is working on my phone. 
Sorry to bother you,
Ben Poile

**Comment by tylermenezes** [comment]
Sorry for any troubles :)
