### ISSUE TITLE
Composer.json fails to autocompile class loaders after cloning

### ISSUE THREAD

**Issue by rodrigoargumedo** [StudentRND/CodeDay#13]
I recently forked this repo and cloned into my VM. So, when I did ``composer install`` to install Laravel and its required dependencies. Just after the components were successfully installed and generate autoload files, Composer complains that some files don't even exist that is required to continue:

     {"error":{"type":"ErrorException","message":"file_get_contents(\/home\/ubuntu\/workspace\/app\/config\/local.json): failed to open stream: No such file or directory",
     "file":"\/home\/ubuntu\/workspace\/app\/config\/app.php","line":3}}
     {"error":{"type":"ErrorException","message":"file_get_contents(\/home\/ubuntu\/workspace\/app\/config\/local.json): failed to open stream: No such file or directory","file":"\/home\/ubuntu\/workspace\/app\/config\/app.php","line":3}}

Is there a way to fix this problem? @tylermenezes

**Comment by tylermenezes** [comment]
Yeah, you need a config file for the app to start properly. I just added a sample config, can you get it working with that?

(There are also a few other things you need to do, `install.sh` will do them / tell you what to do.)

**Comment by tylermenezes** [comment]
Oops, sorry, I thought this was in Clear. Hang on a second and I'll do the same for CodeDay.

**Comment by rodrigoargumedo** [comment]
@tylermenezes: Now, it basically complains Time Zone is invalid, re-specify it in `/home/ubuntu/workspace/vendor/laravel/framework\/src/Illuminate/Foundation/start.php`.

Full error log:

    {"error":{"type":"ErrorException","message":"date_default_timezone_set(): Timezone ID '' is invalid","file":"\/home\/ubuntu\/workspace\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/start.php","line":167}}
    {"error":{"type":"ErrorException","message":"date_default_timezone_set(): Timezone ID '' is invalid","file":"\/home\/ubuntu\/workspace\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/start.php","line":167}}

**Comment by tylermenezes** [comment]
That's usually an indication that there's a problem parsing the `local.json` file. (Ideally this should throw a proper error message...) Can you check your `local.json` file with an online JSON checker?

**Comment by tylermenezes** [comment]
(Note that I think you need to remove the comments for it to be a proper JSON file.)

**Comment by rodrigoargumedo** [comment]
Oh, I will check it out tomorrow and see it if resolves for me.


Sent by Outlook for Android





On Thu, May 21, 2015 at 7:35 PM -0700, "Tyler Menezes" <notifications@github.com> wrote:
(Note that I think you need to remove the comments for it to be a proper JSON file.)

---

**Comment by rodrigoargumedo** [comment]
@tylermenezes It works. Closing this issue.

**Comment by rodrigoargumedo** [comment]
file_get_contents(http://clear.codeday.dev/api/regions/nearby?lat=47&amp;lng=-122&amp;limit=1&amp;with_current_event=1&amp;access_token=&amp;secret=): failed to open stream: Connection refused

**Comment by rodrigoargumedo** [comment]
I'm not using Vagrant or anything fancy.

**Comment by tylermenezes** [comment]
Yes, there's two things going on there:

- You need a local install of Clear
- You need to register an application with that instance, and then add the access key and secret in the config for the website
