### ISSUE TITLE
Location Invalid

### ISSUE THREAD

**Issue by tejasmanohar** [StudentRND/CodeDay#5]
https://codeday.org tells me closest event is Kansas City when it's Nashville.

http://www.whatismyip.com/ reports my correct location in Tennessee.

**Comment by AndrewSB** [comment]
Same, I'm near san francisco and it's telling me my closest event is in Kansas City too

**Comment by tejasmanohar** [comment]
Yeah, saw some other people post about this on FB

**Comment by rodrigoargumedo** [comment]
It's kinda strange that is happening like this one. I'm in Houston but redirects me to Miami. @tylermenezes?

**Comment by LabLayers** [comment]
I'm in Philly with Xfinity and CodeDay thinks that I'm in Kansas City. :+1:

**Comment by tylermenezes** [comment]
Wait, @rodrigoargumedo, is it actually redirecting you, or just telling you the nearest event is somewhere else?

I can't do much about the nearest event being inaccurate unfortunately; it's using an IP geolocation database but it's occasionally inaccurate.

**Comment by rodrigoargumedo** [comment]
It's telling me by nearest location. It's weird.

**Comment by tylermenezes** [comment]
@LabLayers @rodrigoargumedo @tejasmanohar @AndrewSB I switched to a different (aka more expensive) data provider. Let me know if that improves your results.

**Comment by LabLayers** [comment]
Can confirm, it works!

![screen shot 2015-01-02 at 1 37 44 pm](https://cloud.githubusercontent.com/assets/607807/5598457/91c31868-9284-11e4-813b-9c6942f666b4.png)

**Comment by tejasmanohar** [comment]
Yup. Resolved.

**Comment by tjhorner** [comment]
Related: We now use browser geolocation API to get the most accurate location possible.

**Comment by LabLayers** [comment]
Good job @tjhorner

**Comment by tjhorner** [comment]
thank.

**Comment by LabLayers** [comment]
> ![image](https://cloud.githubusercontent.com/assets/607807/10061510/77b0d4ec-6227-11e5-86b2-6cd09dcf5a38.png)

you're welcome

**Comment by rodrigoargumedo** [comment]
@LabLayers Dat TJ logo doe. @tjhorner
